name: build-kernel
on:
  merge_group:
  schedule:
    - cron: "5 0 * * *" # 0005 UTC everyday
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cleanup*.yml'

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      platforms: ${{ matrix.variant.platforms }}
      kernel_flavor: ${{ matrix.variant.kernel_flavor }}
      fedora_version: ${{ matrix.fedora_version }}
    strategy:
      fail-fast: false
      matrix:
        variant:
          - kernel_flavor: asus
            platforms: '["x86_64"]'
          - kernel_flavor: fsync
            platforms: '["x86_64"]'
          - kernel_flavor: fsync-ba
            platforms: '["x86_64"]'
          - kernel_flavor: bazzite
            platforms: '["x86_64", "aarch64"]'
          - kernel_flavor: surface
            platforms: '["x86_64"]'
          - kernel_flavor: main
            platforms: '["x86_64", "aarch64"]'
          - kernel_flavor: coreos-stable
            platforms: '["x86_64", "aarch64"]'
          - kernel_flavor: coreos-testing
            platforms: '["x86_64", "aarch64"]'
        fedora_version:
          - 40
          - 41
        exclude:
          -   { 'fedora_version': 40,  'variant':  {  'kernel_flavor': 'asus',  'platforms': '["x86_64"]' } }
          -   { 'fedora_version': 41,  'variant':  {  'kernel_flavor': 'fsync',  'platforms': '["x86_64"]' } }
          -   { 'fedora_version': 41,  'variant':  {  'kernel_flavor': 'fsync-ba',  'platforms': '["x86_64"]' } }
          -   { 'fedora_version': 40,  'variant':  {  'kernel_flavor': 'bazzite',  'platforms': '["x86_64", "aarch64"]' } }
          -   { 'fedora_version': 40,  'variant':  {  'kernel_flavor': 'coreos-testing',  'platforms': '["x86_64", "aarch64"]' } }

  check:
    name: Check all builds successful
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Exit on failure
        if: ${{ needs.build.result == 'failure' }}
        shell: bash
        run: exit 1
      - name: Exit
        shell: bash
        run: exit 0
