name: aarch64
on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cleanup*.yml'

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-aarch64:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      platform: aarch64
      kernel_flavor: ${{ matrix.kernel_flavor }}
      fedora_version: ${{ matrix.fedora_version }}
    strategy:
      fail-fast: false
      matrix:
        kernel_flavor:
          - bazzite
          - main
          - coreos-stable
          - coreos-testing
        fedora_version:
          - 40
          - 41
        exclude:
          - fedora_version: 40
            kernel_flavor: bazzite
          - fedora_version: 40
            kernel_flavor: coreos-testing
